# Generated by Django 4.2.7 on 2023-11-16 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackendApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTypeDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(blank=True, max_length=50, null=True)),
                ('Product_des', models.CharField(blank=True, max_length=100, null=True)),
                ('Product_image', models.ImageField(blank=True, null=True, upload_to='producttype')),
            ],
        ),
    ]
