# Generated by Django 4.2.7 on 2023-11-16 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackendApp', '0002_producttypedb'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttypedb',
            name='hairname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
