# Generated by Django 4.2.7 on 2023-11-16 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackendApp', '0003_producttypedb_hairname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttypedb',
            name='Product_image',
            field=models.ImageField(blank=True, null=True, upload_to='product_type'),
        ),
    ]
