# Generated by Django 4.2.7 on 2023-11-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackendApp', '0004_alter_producttypedb_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_TypeDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=50, null=True)),
                ('product_name', models.CharField(blank=True, max_length=100, null=True)),
                ('product_des', models.CharField(blank=True, max_length=100, null=True)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='prod')),
            ],
        ),
        migrations.DeleteModel(
            name='ProductTypeDB',
        ),
    ]
