# Generated by Django 4.2.7 on 2023-11-20 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackendApp', '0005_product_typedb_delete_producttypedb'),
    ]

    operations = [
        migrations.CreateModel(
            name='HairproblemDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hair_prblm', models.CharField(blank=True, max_length=50, null=True)),
                ('hairprblm_de', models.CharField(blank=True, max_length=50, null=True)),
                ('prblm_image', models.ImageField(blank=True, null=True, upload_to='prod')),
            ],
        ),
    ]
