# Generated by Django 4.2.7 on 2023-11-22 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackendApp', '0006_hairproblemdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='HairBrandDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hairbrand_name', models.CharField(blank=True, max_length=50, null=True)),
                ('hairbrand_img', models.ImageField(blank=True, null=True, upload_to='brand')),
            ],
        ),
    ]
