# Generated by Django 4.2.7 on 2023-11-25 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BackendApp', '0007_hairbranddb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_typedb',
            name='Name',
        ),
    ]
