# Generated by Django 4.2.7 on 2023-11-25 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackendApp', '0008_remove_product_typedb_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTypeDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(blank=True, max_length=50, null=True)),
                ('product_des', models.CharField(blank=True, max_length=50, null=True)),
                ('product_img', models.ImageField(blank=True, null=True, upload_to='pro')),
            ],
        ),
        migrations.DeleteModel(
            name='product_TypeDB',
        ),
    ]
