# Generated by Django 4.2.7 on 2023-11-25 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackendApp', '0009_producttypedb_delete_product_typedb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_typeDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=50, null=True)),
                ('product_des', models.CharField(blank=True, max_length=50, null=True)),
                ('Product_img', models.ImageField(blank=True, null=True, upload_to='pro')),
            ],
        ),
        migrations.DeleteModel(
            name='ProductTypeDB',
        ),
    ]
