# Generated by Django 4.2.7 on 2023-11-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackendApp', '0010_product_typedb_delete_producttypedb'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddproductDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hairtype_name', models.CharField(blank=True, max_length=50, null=True)),
                ('Problem_name', models.CharField(blank=True, max_length=50, null=True)),
                ('Producttype_name', models.CharField(blank=True, max_length=50, null=True)),
                ('Brand_name', models.CharField(blank=True, max_length=50, null=True)),
                ('Product_name', models.CharField(blank=True, max_length=50, null=True)),
                ('Product_des', models.CharField(blank=True, max_length=50, null=True)),
                ('Prize', models.IntegerField(blank=True, max_length=50, null=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='addpro')),
            ],
        ),
    ]
